### ISSUE TITLE
Ambiguity when zooming in the chromosomes

### ISSUE THREAD

**Issue by homonecloco** [Uauy-Lab/pangenome-web#5]
The chromosomes are not scaled by default. When zooming into a region the position Doesn't match one to one. Hence, the line guiding only applies to the current chromosome. 

Alternative solutions are:

- Show a shadow line with the corresponding solutions
- Shift each variety based on the zoom. Then each line variety is in its own coordinate system. 
- Only display the coordinates based on an specific coordinate system. 

This leads to apparent misalignments like this one: 

![Screenshot 2020-05-13 at 12 43 37](https://user-images.githubusercontent.com/254050/81808284-6638b400-9517-11ea-86a8-3410e2aa9733.png)

**Comment by homonecloco** [comment]
@jemimafb and @uauy , Which of the three options would you prefer. I'm planning to have the option to show all of them, but I would like to prioritise one of them.

**Comment by uauy** [comment]
@homonecloco perhaps we can zoom to discuss the consequences of each option when implementing them.

**Comment by homonecloco** [comment]
This is going to be fixed by adding the shadow line. As computing every position is computational intensive, it will be implemented on 1mbp intervals and interpolation between them.

**Comment by homonecloco** [comment]
A typo in the message closed this buy mistake

**Comment by homonecloco** [comment]
This was fixed when adding  the shadow
