### ISSUE TITLE
Select variety to highlight

### ISSUE THREAD

**Issue by homonecloco** [Uauy-Lab/pangenome-web#6]
Add a way to highlight a variety.   When you click on the cultivar name it should be highlighted highlighted independent of the double click which as I said was a bit difficult for me.

**Comment by uauy** [comment]
Not essential; nice to have

**Comment by homonecloco** [comment]
This is almost implemented.
As a note to myself: I need to make sure that after de-selecting a line, the new default line is the last selection. This avoids an unexpected change in color that may be distracting and makes difficult to save the image from the perspective of X variety.

**Comment by homonecloco** [comment]
This is done by clicking on the name on the variety on the left.
