### ISSUE TITLE
Issues with Edge and cursor

### ISSUE THREAD

**Issue by homonecloco** [Uauy-Lab/pangenome-web#9]
@uauy , please tell me the version of Edge that had issues, so I can have a look. The latest versions are based on chrome

**Comment by uauy** [comment]
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

**Comment by uauy** [comment]
Version 81.0.4044.138 (Official Build) (64-bit)

**Comment by homonecloco** [comment]
This issue duplicates #3

**Comment by homonecloco** [comment]
It seems to still happen. I'm going to remove transitions and use requestAnimationFrame for the mouse interactions.

**Comment by homonecloco** [comment]
Should be fixed by c4db844e849944ba04b2db547e552313c97db731
